---
- name: CREATING THE K8S WORKSTATION
  hosts: all
  become: yes
  gather_facts: false

  tasks:
    - name: DOWNLOADING THE AWS CLI ZIP FILE
    get_url: 
     url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip
     dest: /home/centos/

    - name: INSTALLING UNZIP
    yum:
      name: unzip
      state: latest
    - name: UNZIPPING THE AWS CLI
     unarchive:
        src: /home/centos/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip
        dest: /home/centos/
        remote: ./aws/install --update
 
    - name: DOWNLOADING THE KOPS BINARY
     get_url: 
        url: https://github.com/kubernetes/kops/releases/download/latest/kops-linux-amd
        dest: /usr/local/bin/kops

    - name: MAKES KOPS BINARY EXECUTABLE
     command: chmod +x /usr/local/bin/kops

    - name: DOWNLOADING THE KUBECTL BINARY
     get_url:
         url: https://dl.k8s.io/release/latest/bin/linux/amd64/kubectl
         dest: /usr/local/bin/kubectl

    - name: MAKES KUBECTL BINARY EXECUTABLE
     command: chmod +x /usr/local/bin/kubectl

    - name: GENERATE SSH KEYPAIR
     openssh_keypair: 
     path: /home/centos/.ssh/id_rsa
     state: present

    - name: create k8s cluster
     shell: /usr/local/bin/kops create cluster --yes --state=s3://nalini-k8s --zone=eu-west-1a, eu-west-1b --node-count=2 --name=nalini.k8s.local --ssh-public-key /home/centos/.ssh/id_rsa.pub
...